easydigitaldownloads/edd-amazon-s3

- edd_s3.php
- languages/edd_s3.pot
> Add textdomain. 

- edd_s3.php
Needs Testing. Requires CFM pr https://github.com/chriscct7/edd-checkout-fields/pull/103
> Adds s3 integration for CFM file upload fields.

- edd_s3.php
> link API key notices to appropriate settings page

- edd_s3.php
> update plugin info

- edd_s3.php
> issue/49 - Remove unused local variables

- edd_s3.php
> issue/42 - Add PHP version notice

- edd_s3.php
> issue/57 - Remove call to media_upload_header() to remove legacy media UI

- edd_s3.php
> issue/36 - Use user_nicename instead of user_login for S3 folders

- edd_s3.php
> issue/58 - Add additional metadata about files and buckets

- edd_s3.php
> issue/58 - Ensure owner details exists

- edd_s3.php
> issue/69 - Display message if nothing exists in S3 account

- .gitattributes
- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- Gruntfile.js
- README.md
- grunt/aliases.yaml
- grunt/checktextdomain.js
- grunt/clean.js
- grunt/compress.js
- grunt/copy.js
- grunt/makepot.js
- grunt/potomo.js
- grunt/replace.js
- grunt/wp_readme_to_markdown.js
- languages/edd_s3.pot
- package.json
> issue/72 - Add GitHub files, build files and Git meta files

- .github/CONTRIBUTING.md
Fix the link to the issue tracker in contributing.md
> Issue tracker URL

- edd_s3.php
> Missing / and move code block inside if condition

- edd_s3.php
- includes/class-fes-field.php
> issue/79 - Fix InvalidArgumentException

- class-edd-amazon-s3.php
> issue/82 - Fix conflict with WP Offload S3

- class-edd-amazon-s3.php
> issue/91 - Change is_plugin_active check to class_exists

- class-edd-amazon-s3.php
> issue/90 - Fix pagination when bucket only contains folders

- edd_s3.php
> Don’t load anything if BackupBuddy cron is running

- class-edd-amazon-s3.php
> If $file_name is empty, it’s not an S3 file
